name: sudoku
description: A new Flutter project.
publish_to: 'none'
version: 1.0.10+18

environment:
  sdk: ^3.9.0
  
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_core:
    git:
      url: https://github.com/asserty308/flutter_core.git
      tag_pattern: v{{version}}
    version: ^1.0.7
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1
  intl: ^0.20.2
  package_info_plus: ^8.3.1
  shared_preferences: ^2.5.3
  sudoku_solver_generator: ^2.1.0+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  generate: true

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: 'assets/app_icon.jpg'
  android: true
  ios: true
  web: 
    generate: true
  macos:
    generate: true
  remove_alpha_ios: true
