name: sudoku
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+9

environment:
  sdk: ^3.6.0
  
dependencies:
  cupertino_icons: ^1.0.8
  fast_noise: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  sudoku_solver_generator: ^2.1.0+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  generate: true

  # fonts:
  #   - family: IndieFlower
  #     fonts:
  #       - asset: fonts/IndieFlower/IndieFlower-Regular.ttf

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: 'assets/app_icon.jpg'
  android: true
  ios: true
  web: 
    generate: true
  macos:
    generate: true
  remove_alpha_ios: true
