name: sudoku
description: A new Flutter project.
publish_to: 'none'
version: 0.0.2+5

environment:
  sdk: '>=3.1.0 <4.0.0'
  
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^10.1.1
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  sudoku_solver_generator: ^2.1.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  generate: true

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  web: 
    generate: true
  macos:
    generate: true
  remove_alpha_ios: true
  image_path: 'assets/app_icon.jpg'